---
os: linux
dist: bionic
group: stable vm_type=n1-standard-8

language: java
jdk:
  - openjdk8

install: ./gradlew --parallel build
script: ./gradlew --parallel test

before_cache: gradle/prepCaches.sh
cache:
  directories:
  - $HOME/.gradle

branches:
  only:
    - master
